Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.disk :disk, size: "50GB", primary: true

  config.vm.network "public_network"

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yaml"
      ansible.become = true
      ansible.ask_become_pass = true
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8096"
  end

end
